version: '3.3'
services:
  ser:
    build: .
    ports:
      - "8888:80"
    depends_on:
      - mongo

  mongo:
    image: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: trpg_linker
      expose:
        27017
networks:
  default:
    external:
      name: test-net

